### ISSUE TITLE
Resampling flight data results in a ValueError

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#12]
Hello,
When I try to resample flight data using the built-in method I get a ValueError. 
To reproduce:
```
from traffic.data import opensky
flight = opensky.history("2017-02-05", callsign="EZY158T")
flight2=flight.resample()
```
Gives this error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/traffic/core/flight.py", line 628, in resample
    .resample(rule)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 6835, in interpolate
    **kwargs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 519, in interpolate
    return self.apply('interpolate', **kwargs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 1845, in interpolate
    limit=limit),
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 769, in fillna
    value, method = validate_fillna_kwargs(value, method)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/util/_validators.py", line 348, in validate_fillna_kwargs
    method = clean_fill_method(method)
  File "/network/aopp/apres/users/proud/conda/lib/python3.6/site-packages/pandas/core/missing.py", line 91, in clean_fill_method
    raise ValueError(msg)
ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got linear
```

This is using the latest build of traffic (obtained with: `pip install git+https://github.com/xoolive/traffic`), Pandas version 0.24.1 and python version 3.6.7.

Any ideas what's happening? I tried to diagnose it but have not had any success.

**Comment by xoolive** [comment]
Thank you for the feedback.
I cannot reproduce the issue with my current version of pandas (0.23.4) but will do the upgrade in the coming days.

**Comment by simonrp84** [comment]
No problem.
For what it's worth, I'm running in a conda environment and I know there are some problems when installing pip packages in conda - maybe that happens here.

**Comment by xoolive** [comment]
Coming close, the problem comes from columns with a tz-aware timestamp. (Linear interpolation works ok if we remove those columns)

I had a similar issue with `Flight.query_ehs()` on concatenation with previous version of pandas. (https://github.com/xoolive/traffic/blob/master/traffic/core/flight.py#L314)

I will find a workaround...

**Comment by xoolive** [comment]
Just opened https://github.com/pandas-dev/pandas/issues/25508

**Comment by xoolive** [comment]
@simonrp84 latest commit fixes your issue
