### ISSUE TITLE
RuntimeError: Edit file C:\Users\519\AppData\Local\traffic\traffic\traffic.conf with NM directory  ，how to slove this question ?

### ISSUE THREAD

**Issue by liangx2** [xoolive/traffic#193]
`Traceback (most recent call last):
  File "xxxx\traclus\demo_!.py", line 5, in <module>
    from traffic.data import nm_airspaces
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "D:\anaconda\envs\traffic\lib\site-packages\traffic\data\__init__.py", line 222, in __getattr__
    res = NMAirspaceParser(data=None, config_file=config_file)
  File "D:\anaconda\envs\traffic\lib\site-packages\traffic\data\eurocontrol\ddr\airspaces.py", line 41, in __init__
    self.init_cache()
  File "D:\anaconda\envs\traffic\lib\site-packages\traffic\data\eurocontrol\ddr\airspaces.py", line 51, in init_cache
    raise RuntimeError(msg)
RuntimeError: Edit file C:\Users\519\AppData\Local\traffic\traffic\traffic.conf with NM directory
`

**Comment by xoolive** [comment]
https://traffic-viz.github.io/data_sources/eurocontrol.html

**Comment by liangx2** [comment]
> https://traffic-viz.github.io/data_sources/eurocontrol.html
ok, WindowsPath('C:/Users/519/AppData/Local/traffic/traffic/traffic.conf') this is my path ,will i how to revise it ? i am a rookie.

**Comment by xoolive** [comment]
I doubt you would have access to such data.

**Comment by liangx2** [comment]
So , i can only "from traffic.data import nm_airways, nm_airspaces, nm_navaids, nm_freeroute" ans use this data ?

**Comment by liangx2** [comment]
> I doubt you would have access to such data.

so , i need to sign it to access to such data ?
