### ISSUE TITLE
A problem of numpy.dtype[timedelta64]

### ISSUE THREAD

**Issue by cpt13-g** [xoolive/traffic#307]
Hello, I met a problem. When I run the code, it happens,
```
<class 'pandas.core.series.Series'>
Traceback (most recent call last):
  File "F:\CHD\study\code\plttraffic.py", line 28, in <module>
    ).fit_predict()
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\algorithms\clustering.py", line 136, in fit_predict
    self.X = prepare_features(
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\algorithms\clustering.py", line 44, in prepare_features
    _resampled = traffic.resample(nb_samples).eval(max_workers=max_workers)
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\lazy.py", line 195, in eval
    total = sum(1 for _ in self.wrapped_t.iterate(**self.iterate_kw))
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\lazy.py", line 195, in <genexpr>
    total = sum(1 for _ in self.wrapped_t.iterate(**self.iterate_kw))
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\traffic.py", line 377, in iterate
    yield from Flight(df).split(
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\iterator.py", line 67, in __iter__
    for elt in self.generator:
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\flight.py", line 1268, in split
    for data in _split(self.data, value, unit):
  File "D:\miniconda\envs\traffic\lib\site-packages\traffic\core\flight.py", line 123, in _split
    if max_ > delta:
TypeError: The DType <class 'numpy.dtype[float64]'> could not be promoted by <class 'numpy.dtype[timedelta64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[float64]'>, <class 'numpy.dtype[timedelta64]'>)

Process finished with exit code 1
```

I don't know this error.

**Comment by xoolive** [comment]
Please explain how to reproduce this error
