### ISSUE TITLE
Name 'icao24' is not defined

### ISSUE THREAD

**Issue by HWJ-NUMPY** [xoolive/traffic#474]
Hey Xavier,

---

### **Describe the bug**

I'm following https://traffic-viz.github.io/quickstart.html to learn traffic and I'm encountering an error when using: `console.print(belevingsvlucht)` 
to process the Pandas DataFrame. The column 'icao24' exists in the DataFrame, but when I try to access it, I get following error:

```
Traceback (most recent call last):
  File "/Users/wenjiehe/PycharmProjects/Traffic/Flight_Objects.py", line 10, in <module>
    console.print(belevingsvlucht)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/rich/console.py", line 1705, in print
    extend(render(renderable, render_options))
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/rich/console.py", line 1326, in render
    for render_output in iter_render:
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/traffic/core/flight.py", line 452, in __rich_console__
    if self.aircraft is not None:
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/traffic/core/flight.py", line 1239, in aircraft
    return aircraft.get(self.icao24)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/traffic/data/basic/aircraft.py", line 292, in get
    df = self[name]
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/traffic/data/basic/aircraft.py", line 265, in __getitem__
    df = self.data.query(
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/frame.py", line 4823, in query
    res = self.eval(expr, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/frame.py", line 4949, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/eval.py", line 336, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 805, in __init__
    self.terms = self.parse()
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 824, in parse
    return self._visitor.visit(self.expr)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 420, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 742, in visit_BoolOp
    return reduce(visitor, operands)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 735, in visitor
    lhs = self._try_visit_binop(x)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 731, in _try_visit_binop
    return self.visit(bop)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 715, in visit_Compare
    return self.visit(binop)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 531, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 451, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 541, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 91, in __init__
    self._value = self._resolve_name()
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(local_name, is_local=is_local)
  File "/opt/anaconda3/envs/traffic/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 244, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.errors.UndefinedVariableError: name 'icao24' is not defined
```

---

### **To Reproduce the bug**

I installed 'traffic' with:
```
conda create -n traffic -c conda-forge python=3.10 traffic
conda activate traffic
```

And my Code is:
```
from traffic.data.samples import belevingsvlucht
from rich.pretty import pprint
from rich.console import Console

print(belevingsvlucht)
pprint(belevingsvlucht)

# Error: pandas.errors.UndefinedVariableError: name 'icao24' is not defined
console = Console()
console.print(belevingsvlucht)
```
---

### **Version**

- Python: 3.10.15
- traffic: 2.10.2
- rich: 13.9.4
- pandas: 2.2.3

**Comment by xoolive** [comment]
Hi @HWJ-NUMPY 

I just tried with the latest release (on MacOS, I don't have a Windows at hand)

<img width="430" alt="Capture d’écran 2024-11-18 à 23 34 37" src="https://github.com/user-attachments/assets/0cdc647a-f81a-4955-b4c7-5f2b8e9c3a6e">

It seems to work, but note that I still didn't manage to publish the latest release on conda (because of one dependency that is not available there yet)

You want to try to `pip install --upgrade traffic` in your environment and try again

**Comment by HWJ-NUMPY** [comment]
Hi Xavier,

Thank you for your help! 

I tried `pip install --upgrade traffic` and then ran the code, but it still didn't work.

![image](https://github.com/user-attachments/assets/189339f8-5c72-432e-a4a1-b0fa5d44d181)

I have tried it on both my macOS laptop and Windows PC and also on my friend's Windows PC, but I keep getting this error.

**Comment by xoolive** [comment]
Oh I see, I suspect it's a problem in your aircraft database, I had to fix the link to the aircraft database. Can you check you have [this fix](https://github.com/xoolive/traffic/commit/2da8c885f63d3afb07a25eb5e74128aa3349cd24) in your code base?

In case this is not enough, I am sorry I can't reproduce and I must say I have to stop supporting conda until next traffic release (I promise it will work again). With MacOS or Linux (maybe Windows too, but I can't say for sure), I recommend you try [uv](https://astral.sh/uv) and run the command in my screenshot.

**Comment by HWJ-NUMPY** [comment]
Thank you for your quick reply!

I have fixed the link of aircraft database:

![image](https://github.com/user-attachments/assets/2a5bbfbe-724d-4224-a22a-708d97d0e001)

And then I used the `uv run --with traffic python`, but unfortunately I still got this error:

![image](https://github.com/user-attachments/assets/6f734e46-5da4-4ddb-b3ee-4d8c9c44109f)
![image](https://github.com/user-attachments/assets/062c26b6-b13f-46d5-a3be-4f44fc2b98ce)

Maybe the problem is here in aircraft.py？

  ```
def __getitem__(self: T, name: str | list[str]) -> None | T:
      """Requests an aircraft by icao24 or registration (exact match)."""

      if isinstance(name, str):
          df = self.data.query(
              "icao24 == @name.lower() or registration == @name.upper()"
          )
      else:
          df = self.data.query("icao24 in @name or registration in @name")
      if df.shape[0] == 0:
          return None
      return self.__class__(df)
```

The name "icao24" is not recognizable. But when I `print(belevingsvlucht.data)`, 'icao24' is shown in the DataFrame.

![image](https://github.com/user-attachments/assets/5980440f-0bbc-4772-8539-4add1bdb2560)

**Comment by xoolive** [comment]
Please try with the HEAD version of the repository. If you had to edit the code, it means you are not up to date.

**Comment by MICHELEVELLA** [comment]
It seems I have the same problem on the mac version regarding the icao24 not being found. I also updated the link of database manually.

![Screenshot 2024-12-12 at 15 32 04](https://github.com/user-attachments/assets/b86c1f2b-dcd7-4155-b96d-dbb7b9d6cd80)

**Comment by HWJ-NUMPY** [comment]
> It seems I have the same problem on the mac version regarding the icao24 not being found. I also updated the link of database manually.
> 
> ![Screenshot 2024-12-12 at 15 32 18](https://private-user-images.githubusercontent.com/145723288/395202411-4c34dd2a-57ac-4aa8-bbf0-488b1b2a5866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODg3MDYsIm5iZiI6MTczNDA4ODQwNiwicGF0aCI6Ii8xNDU3MjMyODgvMzk1MjAyNDExLTRjMzRkZDJhLTU3YWMtNGFhOC1iYmYwLTQ4OGIxYjJhNTg2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxMTEzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjI4YzJiY2RmOTllYmFiNTczZjViYjMxNTI5NmFiM2JkMmEzZjAzYzEzYzgyZDQ3Y2EyYzAzMTEyNzg4ZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6CLC3KFzrfUOCs-qynYzSRLZAcsykWq0nNJw8XrdS0Q)

I've also tried it on a Windows PC and got the same error. Still don't know how to fix it :(

**Comment by xoolive** [comment]
Hi all, I can't reproduce the bug you mention with HEAD version of the repository (on Linux and MacOS).
Can you try to remove the cache file for your aircraft database as it may be corrupted?

The file name is `opensky_db.pkl` in the cache folder that you can identify from:
```python
from traffic.data import aircraft
aircraft.cache_dir
```

In the next release to come, I will change that file to parquet format. So if you wait enough for it, it will download a new file since the extension in the cache folder will be wrong.

**Comment by xoolive** [comment]
Please try traffic 2.11.1, it's available on pip, should be on conda in the coming hours

**Comment by xoolive** [comment]
Reopen the issue if not solved
