### ISSUE TITLE
traffic module is not available

### ISSUE THREAD

**Issue by ChenhuiAn-git** [xoolive/traffic#77]
Hello, I recently needed to access the data on the opensky network. After installing the traffic module according to the requirements, running the sample program in the document found that the traffic module was unavailable and many errors occurred. Just enter the code of the imported module and one line of code will give an error.
`import traffic `
The errors that appear are as follows, what is causing this, thank you very much! Other examples on the official documentation will not work.

```
C:\Users\Administrator\Anaconda3\envs\evn-traffic\python.exe C:/Users/Administrator/Desktop/traffic-test/traffic-ce001.py
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/traffic-test/traffic-ce001.py", line 4, in <module>
    import traffic
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\traffic\__init__.py", line 8, in <module>
    import pkg_resources
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\pkg_resources\__init__.py", line 80, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\win32\lib\pywintypes.py", line 137, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\Administrator\Anaconda3\envs\evn-traffic\lib\site-packages\win32\lib\pywintypes.py", line 40, in __import_pywin32_system_module__
    for suffix_item in imp.get_suffixes():
AttributeError: module 'importlib' has no attribute 'get_suffixes'
```

**Comment by xoolive** [comment]
Thank you for your feedback.

The problem seems to be out of control of `traffic` as it is in one dependency of `pkg_resources` which comes with `setuptools`.

Things you could try:
- check your Python version (should be >= 3.6)
- try again from a fresh conda environment (I see you made one for that already, but I am pretty helpless here...)
- `pip install -U setuptools`  # upgrade to latest version of setuptools
- if nothing helps: comment **line 8** in `traffic/__init__.py` and **from line 99 to the end of the file**; then `pip install .` again. You won't have access to plugins (see documentation) but this issue won't hamper your work.

If you encounter more problems, I would appreciate details about your platform (OS, 32/64bits, python version, etc.)

**Comment by ChenhuiAn-git** [comment]
> 感谢您的反馈意见。
> 
> 这个问题似乎失控了，`traffic`因为它`pkg_resources`伴随着一种依赖`setuptools`。
> 
> 您可以尝试的事情：
> 
> * 检查您的Python版本（应为> = 3.6）
> * 在新的conda环境中再试一次（我看到您已经为此创建了一个，但是我在这里很无助...）
> * `pip install -U setuptools`  ＃升级到最新版本的setuptools
> * 如果没有帮助：在**第99 ****行**`traffic/__init__.py`以及**从第99行到文件末尾的第****8 ****行**注释；然后`pip install .`再来。您将无权使用插件（请参阅文档），但是此问题不会妨碍您的工作。
> 
> 如果您遇到更多问题，不胜感激，有关您的平台的详细信息（操作系统，32/64位，python版本等）

Thank you very much for receiving your reply. I tried your suggestions but still didn't solve the problem. Also, I tried various methods and still couldn't download your traffic module from GitHub. Thank you for sending the traffic module to my mailbox. I tried to remove and reinstall the anaconda3 software, and executed the `import traffic` statement again, and a new error appeared, as shown below. Thanks again for your answers.

```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/CAT021数据解析程序-遍历txt文件/ModeS-jiema/00.py", line 1, in <module>
    import traffic
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\traffic\__init__.py", line 102, in <module>
    handle = entry_point.load()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ipywidgets 7.4.2 (c:\users\administrator\anaconda3\lib\site-packages), Requirement.parse('ipywidgets<8,>=7.5.0'), {'ipyleaflet'})
```

**Comment by xoolive** [comment]
Your error is line 102. I suggested in my previous comment that you comment from line 99 until the end of the file.

**Comment by ChenhuiAn-git** [comment]
> Your error is line 102. I suggested in my previous comment that you comment from line 99 until the end of the file.
> 
> Apart from that, if you read your `ContextualVersionConflict` it says you should upgrade your version of `ipywidgets`: `pip install -U ipywidgets`

Annotate the contents of __init__.py according to your method, and `import traffic` can be used. But an hour later, when using `import traffic` again, a new error occurred. I am a newbie and tried some methods and still haven't solved the new errors, thanks again for your answers.
```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/CAT021数据解析程序-遍历txt文件/ModeS-jiema/ceshi_lianxi.py", line 8, in <module>
    import traffic
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\__init__.py", line 9, in <module>
    from appdirs import user_cache_dir, user_config_dir
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\appdirs-1.4.3-py3.7.egg\appdirs.py", line 560, in <module>
    import win32com.shell
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\win32\lib\pywintypes.py", line 137, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "D:\anaconda3\envs\env-pymodes-opensky\lib\site-packages\win32\lib\pywintypes.py", line 40, in __import_pywin32_system_module__
    for suffix_item in imp.get_suffixes():
AttributeError: module 'importlib' has no attribute 'get_suffixes'
```

**Comment by xoolive** [comment]
This is not a problem with traffic but with your installation. The errors occur upon importing external dependencies. Can’t be of much help here. If you have too much trouble maintaining your system, consider running the library in a vanilla virtual machine.
